apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: splunk-dev
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/dev/splunk
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  targetNamespace: splunk
  wait: true
  timeout: 5m
